server {
    listen 80;

    # Serve static files from the React build directory
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Handle React routing (fallback to index.html for 404s)
        try_files $uri $uri/ /index.html;
    }

    # We are calling the Public Backend IP directly from React now, so no proxy needed.

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
