trigger:
  branches:
    include:
      - main

stages:
- stage: BuildPushUpdate
  jobs:
  - job: BuildAndPush
    pool:
      name: local-agent

    steps:

    - checkout: self

    - task: AzureCLI@2
      displayName: Login to Azure Container Registry
      inputs:
        azureSubscription: AzureServiceConnection
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Logging into Azure Container Registry"
          az acr login --name mywallet

    - task: CmdLine@2
      displayName: Build Backend Image
      inputs:
        script: |
          echo "Building backend docker image"
          docker build -t mywallet.azurecr.io/mywallet-backend:$(Build.BuildId) ./backend

    - task: CmdLine@2
      displayName: Build Frontend Image
      inputs:
        script: |
          echo "Building frontend docker image"
          docker build -t mywallet.azurecr.io/mywallet-frontend:$(Build.BuildId) ./frontend

    - task: CmdLine@2
      displayName: Push Backend Image
      inputs:
        script: |
          echo "Pushing backend image"
          docker push mywallet.azurecr.io/mywallet-backend:$(Build.BuildId)

    - task: CmdLine@2
      displayName: Push Frontend Image
      inputs:
        script: |
          echo "Pushing frontend image"
          docker push mywallet.azurecr.io/mywallet-frontend:$(Build.BuildId)

    - task: CmdLine@2
      displayName: Update GitOps Repository
      inputs:
        script: |
          echo "Cloning GitOps repository"

          git clone https://$(GITOPS_TOKEN)@github.com/Rayudu0729/mywallet-gitops.git

          cd mywallet-gitops

          echo "Updating backend image"
          sed -i "s|mywallet.azurecr.io/mywallet-backend:.*|mywallet.azurecr.io/mywallet-backend:$(Build.BuildId)|g" backend/deployment.yaml

          echo "Updating frontend image"
          sed -i "s|mywallet.azurecr.io/mywallet-frontend:.*|mywallet.azurecr.io/mywallet-frontend:$(Build.BuildId)|g" frontend/deployment.yaml

          git config user.email "devops@mywallet.com"
          git config user.name "azure-devops"

          git add .
          git commit -m "Update images to $(Build.BuildId)"
          git push