spring.main.allow-circular-references=true

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://trolley.proxy.rlwy.net:44881/expensetracker
spring.datasource.username=root
spring.datasource.password=WYvciQXmjuTpyeXkwrLlQCBtAjmZvDPD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

app.jwtSecret= ======================expense=tracker=mywallet===========================
app.jwtExpirationMs=86400000

spring.mail.host=email-smtp.ap-south-1.amazonaws.com
spring.mail.port=587
spring.mail.username=AKIATZNNBJXK36TX3AKL

spring.mail.password=BKYEk8ZrNviRWb0LLgvQJWUSw4vUt5z/eoSb061O3ac8
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.verificationCodeExpirationMs=60000
app.mail.from=noreply@pockethrms.com
app.user.profile.upload.dir=./uploads/user/profile
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

app.cors.allowed-origins=http://localhost:3000
