import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

/**
 * Exports a monthly expense report as a PDF file.
 * @param {{ income, expense, savings, txCount, categorySummary, monthName, year }} reportData
 */
export function exportPdf({ income, expense, savings, txCount, categorySummary, monthName, year }) {
    const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
    const pageW = doc.internal.pageSize.getWidth();

    // ── Header ──────────────────────────────────────────────────────────────
    doc.setFillColor(10, 20, 40);
    doc.rect(0, 0, pageW, 36, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.setTextColor(52, 211, 153);
    doc.text("MyWallet", 14, 16);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(148, 163, 184);
    doc.text("Monthly Expense Report", 14, 24);

    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(`Period: ${monthName} ${year}`, 14, 31);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageW - 14, 31, { align: "right" });

    // ── Summary Table ────────────────────────────────────────────────────────
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(30, 30, 30);
    doc.text("Summary", 14, 48);

    autoTable(doc, {
        startY: 52,
        head: [["Metric", "Amount"]],
        body: [
            ["Total Income", `Rs. ${income.toLocaleString()}`],
            ["Total Expense", `Rs. ${expense.toLocaleString()}`],
            ["Net Savings", `Rs. ${savings.toLocaleString()}`],
            ["No. of Transactions", txCount.toString()],
        ],
        headStyles: { fillColor: [10, 20, 40], textColor: [52, 211, 153], fontStyle: "bold" },
        alternateRowStyles: { fillColor: [245, 247, 250] },
        columnStyles: { 0: { cellWidth: 80 }, 1: { halign: "right" } },
        styles: { fontSize: 11, cellPadding: 5 },
    });

    // ── Category Breakdown ───────────────────────────────────────────────────
    if (categorySummary.length > 0) {
        const afterSummary = doc.lastAutoTable.finalY + 12;
        doc.setFont("helvetica", "bold");
        doc.setFontSize(12);
        doc.setTextColor(30, 30, 30);
        doc.text("Category Breakdown (Expenses)", 14, afterSummary);

        const totalExp = categorySummary.reduce((s, c) => s + c.amount, 0) || 1;

        autoTable(doc, {
            startY: afterSummary + 4,
            head: [["Category", "Amount (Rs.)", "% of Expense"]],
            body: categorySummary.map(c => [
                c.name,
                c.amount.toLocaleString(),
                `${((c.amount / totalExp) * 100).toFixed(1)}%`
            ]),
            headStyles: { fillColor: [10, 20, 40], textColor: [52, 211, 153], fontStyle: "bold" },
            alternateRowStyles: { fillColor: [245, 247, 250] },
            columnStyles: { 1: { halign: "right" }, 2: { halign: "right" } },
            styles: { fontSize: 10, cellPadding: 4 },
        });
    }

    // ── Footer ───────────────────────────────────────────────────────────────
    const pageH = doc.internal.pageSize.getHeight();
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184);
    doc.text("Generated by MyWallet — Your Personal Finance Manager", pageW / 2, pageH - 8, { align: "center" });

    doc.save(`MyWallet-Report-${monthName}-${year}.pdf`);
}
